/**
 * AI Service - Real AI Integration for NCR Local Guide Bot
 * 
 * This module provides TRUE AI-powered responses using OpenAI/Anthropic APIs
 * with product.md context and steering guidelines.
 * 
 * KIRO AGENTIC DEVELOPMENT:
 * - Generated by Kiro AI Agent on December 28, 2025
 * - Implements design patterns from .kiro/specs/ncr-guide-bot/design.md
 * - Uses context from .kiro/product.md
 * - Applies steering from .kiro/steering/ncr-guide-behavior.md
 * 
 * This demonstrates Kiro's true agentic capabilities:
 * - Real-time AI response generation
 * - Dynamic context integration
 * - Steering-guided behavior
 */

const fs = require('fs');
const path = require('path');

class AIService {
  constructor() {
    this.productContext = null;
    this.steeringGuidelines = null;
    this.apiKey = process.env.OPENAI_API_KEY || process.env.ANTHROPIC_API_KEY || process.env.GEMINI_API_KEY;
    this.provider = process.env.AI_PROVIDER || 'openai'; // 'openai', 'anthropic', or 'gemini'
    
    this.loadContext();
  }

  /**
   * Load product.md context and steering guidelines
   */
  loadContext() {
    try {
      // Load product context
      const productPath = path.join(__dirname, '../.kiro/product.md');
      this.productContext = fs.readFileSync(productPath, 'utf-8');
      
      // Load steering guidelines
      const steeringPath = path.join(__dirname, '../.kiro/steering/ncr-guide-behavior.md');
      this.steeringGuidelines = fs.readFileSync(steeringPath, 'utf-8');
      
      console.log('✅ AI Service: Loaded context and steering guidelines');
    } catch (error) {
      console.error('❌ AI Service: Failed to load context:', error.message);
      throw error;
    }
  }

  /**
   * Generate AI response using OpenAI API
   */
  async generateWithOpenAI(query) {
    const systemPrompt = this.buildSystemPrompt();
    
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${this.apiKey}`
      },
      body: JSON.stringify({
        model: 'gpt-4o-mini', // Fast and cost-effective
        messages: [
          {
            role: 'system',
            content: systemPrompt
          },
          {
            role: 'user',
            content: query
          }
        ],
        temperature: 0.8, // Creative but consistent
        max_tokens: 500
      })
    });

    if (!response.ok) {
      throw new Error(`OpenAI API error: ${response.statusText}`);
    }

    const data = await response.json();
    return {
      text: data.choices[0].message.content,
      model: data.model,
      provider: 'OpenAI',
      usage: data.usage
    };
  }

  /**
   * Generate AI response using Anthropic Claude API
   */
  async generateWithAnthropic(query) {
    const systemPrompt = this.buildSystemPrompt();
    
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': this.apiKey,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: 'claude-3-haiku-20240307', // Fast and cost-effective
        max_tokens: 500,
        system: systemPrompt,
        messages: [
          {
            role: 'user',
            content: query
          }
        ]
      })
    });

    if (!response.ok) {
      throw new Error(`Anthropic API error: ${response.statusText}`);
    }

    const data = await response.json();
    return {
      text: data.content[0].text,
      model: data.model,
      provider: 'Anthropic',
      usage: data.usage
    };
  }

  /**
   * Generate AI response using Google Gemini API
   */
  async generateWithGemini(query) {
    const systemPrompt = this.buildSystemPrompt();
    
    // Gemini uses a different URL structure with API key in URL
    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${this.apiKey}`;
    
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: `${systemPrompt}\n\nUser Query: ${query}`
              }
            ]
          }
        ],
        generationConfig: {
          temperature: 0.8,
          maxOutputTokens: 500,
          topP: 0.95,
          topK: 40
        }
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Gemini API error: ${response.statusText} - ${errorText}`);
    }

    const data = await response.json();
    
    // Gemini response structure is different
    const text = data.candidates[0].content.parts[0].text;
    
    return {
      text: text,
      model: 'gemini-1.5-flash',
      provider: 'Google Gemini',
      usage: {
        promptTokens: data.usageMetadata?.promptTokenCount || 0,
        completionTokens: data.usageMetadata?.candidatesTokenCount || 0,
        totalTokens: data.usageMetadata?.totalTokenCount || 0
      }
    };
  }

  /**
   * Build system prompt with context and steering
   */
  buildSystemPrompt() {
    return `You are Kiro, a friendly and knowledgeable local guide for Delhi NCR (National Capital Region).

# YOUR CONTEXT (NCR Knowledge Base):
${this.productContext}

# YOUR BEHAVIOR GUIDELINES:
${this.steeringGuidelines}

# IMPORTANT INSTRUCTIONS:
1. Use Hinglish (Hindi mixed with English) naturally
2. Be friendly, casual, and approachable
3. Address users as "bhai", "yaar", "dost", or "bhabhi"
4. Include specific locations, prices, and timings from the context
5. Use emojis to make responses engaging
6. Keep responses practical and actionable
7. If the query is not about NCR, politely redirect

# RESPONSE FORMAT:
- Start with a friendly greeting or acknowledgment
- Provide specific, actionable information
- Include prices, locations, and timings when relevant
- End with a helpful follow-up question or suggestion

Now respond to the user's query using this context and guidelines.`;
  }

  /**
   * Generate AI-powered response
   * This is the main method that demonstrates true agentic AI
   */
  async generateResponse(query) {
    try {
      console.log(`🤖 AI Service: Generating response for: "${query}"`);
      
      let result;
      
      if (this.provider === 'anthropic') {
        result = await this.generateWithAnthropic(query);
      } else if (this.provider === 'gemini') {
        result = await this.generateWithGemini(query);
      } else {
        result = await this.generateWithOpenAI(query);
      }
      
      console.log(`✅ AI Service: Response generated using ${result.provider}`);
      
      return {
        response: result.text,
        metadata: {
          source: `${result.provider} AI Agent`,
          model: result.model,
          provider: result.provider,
          generatedAt: new Date().toISOString(),
          contextUsed: 'product.md + ncr-guide-behavior.md',
          usage: result.usage
        }
      };
      
    } catch (error) {
      console.error('❌ AI Service: Error generating response:', error.message);
      throw error;
    }
  }

  /**
   * Check if AI service is properly configured
   */
  isConfigured() {
    return this.apiKey && this.productContext && this.steeringGuidelines;
  }
}

module.exports = AIService;
